version: '3'

services:

    app:
        build: .
        container_name: bichos-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: bichos-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: bichos-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=bichos
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bichos-phpmyadmin
        restart: unless-stopped
        ports:
        - "8012:80"
        depends_on:
        - db
        networks:
        - app-network

    redis:
        image: redis:alpine
        container_name: bichos-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
